version: '3.8'
services:
  app:
    build: .
    restart: always
    volumes:
      - ./:/home/app
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - database
      - redis1
      - redis2
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_DATABASE_PASSWORD}
      - POSTGRES_USER=${TYPEORM_DATABASE_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE_NAME}
    ports:
      - ${TYPEORM_DATABASE_PORT}:${TYPEORM_DATABASE_PORT}
    volumes:
      - db:/var/lib/pgpsql/data
    networks:
      - backend
  redis1:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis1:/var/lib/redis1
    networks:
      - backend
  redis2:
    image: redis:latest
    restart: always
    volumes:
      - redis2:/var/lib/redis2
    ports:
      - ${REDIS_MICROSERVICE_PORT}:${REDIS_MICROSERVICE_PORT}
    networks:
      - backend
volumes:
  db: {}
  redis1: {}
  redis2: {}
networks:
  backend:
    driver: bridge
